version: "3.9"

services:
  nginx:
    image: nginx:latest
    container_name: nginx_gateway
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - auth_blue
      - auth_green
      - data

  auth_blue:
    build:
      context: ./services/auth-service
    container_name: "auth_blue"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@localhost:6543/auth_service_nginx?schema=public
      - SERVICE_VERSION=blue
      - PORT=3000
    volumes:
      - ./services/auth-service/src:/app/src
      - ./services/auth-service/prisma:/app/prisma

  auth_green:
    build:
      context: ./services/auth-service
    container_name: "auth_green"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@localhost:6543/auth_service_nginx?schema=public
      - SERVICE_VERSION=green
      - PORT=3000
    volumes:
      - ./services/auth-service/src:/app/src
      - ./services/auth-service/prisma:/app/prisma

  data:
    image: python:3.11-slim
    container_name: data_api
    working_dir: /app
    volumes:
      - ./services/data-service:/app
    command:
      [
        "sh",
        "-c",
        "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000",
      ]
